### ISSUE TITLE
Headings not in proper hierarchy

### ISSUE THREAD

**Issue by DoofusMoofus** [Sandvich/puppykit#1]
Header tags should be placed in an hierarchical manner without any skips in levels. E.g.

```
<h1>Page title</h1>
<h2>Content header</h2>
<h2>Content header</h2>
<h3>Nested content header</h3>
<h2>Content header</h2>
```

Right now there are h3s directly under the h1 which I assume was done for styling purposes. I recommend instead having CSS classes which control the styling of the headers because the style of the header does not necessarily correlate with the header hierarchy.

But what if there's a heading required for hierarchy that I don't want to display visually?

You can do something like this:

.hide-visually{
    position: absolute;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(0 0 0 0);
    margin: -1px;
    padding: 0;
    border: 0;
}

`<h1 class="hide-visually">Page title that I don't want to show</h1>`

This will hide the content visually but make them still accessible to screen readers. Note that using display:none; won't work as screen readers will ignore the text altogether.

**Comment by Sandvich** [comment]
Fixed in 516715b4db3fb6d43037c9e7064f74141ad9a2bb
